-- MySQL Script generated by MySQL Workbench
-- Mon May 26 08:37:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FrontGround`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FrontGround` (
  `Colision_Type` BLOB NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Contents` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Colision_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `Id_Game` VARCHAR(45) NOT NULL,
  `Name` TEXT(10) NOT NULL,
  `Amount_Horney` TINYINT(20) NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  `FrontGround_Colision_Type` BLOB NOT NULL,
  PRIMARY KEY (`Id_Game`, `FrontGround_Colision_Type`),
  INDEX `fk_Game_FrontGround1_idx` (`FrontGround_Colision_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Game_FrontGround1`
    FOREIGN KEY (`FrontGround_Colision_Type`)
    REFERENCES `mydb`.`FrontGround` (`Colision_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BackGround`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BackGround` (
  `Id_BackGround` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Game_Id_Game` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_BackGround`, `Game_Id_Game`),
  INDEX `fk_BackGround_Game1_idx` (`Game_Id_Game` ASC) VISIBLE,
  CONSTRAINT `fk_BackGround_Game1`
    FOREIGN KEY (`Game_Id_Game`)
    REFERENCES `mydb`.`Game` (`Id_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Characters` (
  `id_Character` VARCHAR(45) NOT NULL,
  `Sprite` BLOB NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Pos_Y` VARCHAR(45) NOT NULL,
  `Pos_X` VARCHAR(45) NOT NULL,
  `Animation` BLOB NOT NULL,
  `Healt_bar` TINYINT(10) NULL,
  `Game_Id_Game` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Character`, `Game_Id_Game`),
  INDEX `fk_Characters_Game1_idx` (`Game_Id_Game` ASC) VISIBLE,
  CONSTRAINT `fk_Characters_Game1`
    FOREIGN KEY (`Game_Id_Game`)
    REFERENCES `mydb`.`Game` (`Id_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NPC` (
  `Id_Npc` VARCHAR(45) NOT NULL,
  `Characters_id_Character` VARCHAR(45) NOT NULL,
  `Text_Box` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Npc`, `Characters_id_Character`),
  INDEX `fk_NPC_Characters_idx` (`Characters_id_Character` ASC) VISIBLE,
  CONSTRAINT `fk_NPC_Characters`
    FOREIGN KEY (`Characters_id_Character`)
    REFERENCES `mydb`.`Characters` (`id_Character`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `id_Player` VARCHAR(45) NOT NULL,
  `Characters_id_Character` VARCHAR(45) NOT NULL,
  `Jump` BLOB NOT NULL,
  `Speed` INT NOT NULL,
  PRIMARY KEY (`id_Player`, `Characters_id_Character`),
  INDEX `fk_Player_Characters1_idx` (`Characters_id_Character` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Characters1`
    FOREIGN KEY (`Characters_id_Character`)
    REFERENCES `mydb`.`Characters` (`id_Character`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enemy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enemy` (
  `idInimigo` INT NOT NULL,
  `Tipe` VARCHAR(45) NOT NULL,
  `MoveSet` VARCHAR(45) NOT NULL,
  `Characters_id_Character` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInimigo`, `Characters_id_Character`),
  INDEX `fk_Inimigo_Characters1_idx` (`Characters_id_Character` ASC) VISIBLE,
  CONSTRAINT `fk_Inimigo_Characters1`
    FOREIGN KEY (`Characters_id_Character`)
    REFERENCES `mydb`.`Characters` (`id_Character`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plataform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plataform` (
  `idPlataforma` VARCHAR(45) NOT NULL,
  `Pos_X` VARCHAR(45) NOT NULL,
  `Pos_Y` VARCHAR(45) NOT NULL,
  `Largura` INT NOT NULL,
  `Altura` INT NOT NULL,
  `FrontGround_Colision_Type` BLOB NOT NULL,
  PRIMARY KEY (`idPlataforma`, `FrontGround_Colision_Type`),
  INDEX `fk_Plataform_FrontGround1_idx` (`FrontGround_Colision_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Plataform_FrontGround1`
    FOREIGN KEY (`FrontGround_Colision_Type`)
    REFERENCES `mydb`.`FrontGround` (`Colision_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Honey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Honey` (
  `Id_honey` VARCHAR(45) NOT NULL,
  `Pos_X` VARCHAR(45) NOT NULL,
  `Pos_Y` VARCHAR(45) NOT NULL,
  `FrontGround_Colision_Type` BLOB NOT NULL,
  PRIMARY KEY (`Id_honey`, `FrontGround_Colision_Type`),
  INDEX `fk_Honey_FrontGround1_idx` (`FrontGround_Colision_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Honey_FrontGround1`
    FOREIGN KEY (`FrontGround_Colision_Type`)
    REFERENCES `mydb`.`FrontGround` (`Colision_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hose` (
  `id_Hose` VARCHAR(45) NOT NULL,
  `Pos_x` VARCHAR(45) NOT NULL,
  `Pos_Y` VARCHAR(45) NOT NULL,
  `Active` TINYINT NOT NULL,
  `FrontGround_Colision_Type` BLOB NOT NULL,
  PRIMARY KEY (`id_Hose`, `FrontGround_Colision_Type`),
  INDEX `fk_Hose_FrontGround1_idx` (`FrontGround_Colision_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Hose_FrontGround1`
    FOREIGN KEY (`FrontGround_Colision_Type`)
    REFERENCES `mydb`.`FrontGround` (`Colision_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
